title: "AstroStat School 2026 — Rome"
author: "AstroStat Academy"
copyright: "2026"

repository:
  url: https://github.com/AstroStat-Academy/astrostat-school-7
  path_to_book: .
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
    - amsmath
